name: Deploy Backend to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t backend-repo .

    - name: Tag Docker Image
      run: docker tag backend-repo:latest 340325702627.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

    - name: Push Image to ECR
      run: docker push 340325702627.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
        --cluster ECS-cluster \
        --service backend-task-service \
        --force-new-deployment
